# Generated by Django 6.0.2 on 2026-03-02 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_city_state_remove_supplier_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Readymade_Food',
        ),
    ]
