# Generated by Django 6.0.2 on 2026-03-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_delete_readymade_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverages',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='condiments',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dairy',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fresh_produce',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='grains',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='household_supplies',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='personal_care',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='snacks',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stationery',
            name='cost',
            field=models.IntegerField(null=True),
        ),
    ]
