# Generated by Django 6.0.2 on 2026-03-03 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_beverages_cost_condiments_cost_dairy_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condiments',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='dairy',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='fresh_produce',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='grains',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='household_supplies',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='personal_care',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='snacks',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='stationery',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='Beverages',
        ),
        migrations.DeleteModel(
            name='Condiments',
        ),
        migrations.DeleteModel(
            name='Dairy',
        ),
        migrations.DeleteModel(
            name='Fresh_Produce',
        ),
        migrations.DeleteModel(
            name='Grains',
        ),
        migrations.DeleteModel(
            name='Household_Supplies',
        ),
        migrations.DeleteModel(
            name='Personal_Care',
        ),
        migrations.DeleteModel(
            name='Snacks',
        ),
        migrations.DeleteModel(
            name='Stationery',
        ),
    ]
