# Generated by Django 6.0.2 on 2026-03-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stockitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitems',
            name='type',
            field=models.CharField(choices=[('Fr', 'Fresh Produce'), ('Gr', 'Grains'), ('Dr', 'Dairy'), ('Cn', 'Condiments'), ('Sn', 'Snacks'), ('Bv', 'Beverages'), ('Pc', 'Personal Care'), ('Hs', 'Household supplies'), ('St', 'Stationery')], default='Fr', max_length=2),
        ),
    ]
