# Generated by Django 6.0.2 on 2026-03-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_stockitems_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='stockitems',
            constraint=models.UniqueConstraint(fields=('name', 'supplier'), name='unique_product'),
        ),
    ]
