# Generated by Django 6.0.2 on 2026-03-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_supplier_name_stockitems_unique_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitems',
            name='cost',
            field=models.IntegerField(null=True, verbose_name='Cost(Per Unit)'),
        ),
        migrations.AlterField(
            model_name='stockitems',
            name='quantity',
            field=models.CharField(max_length=20, verbose_name='Quantity(Per Unit)'),
        ),
    ]
