# Generated by Django 6.0.2 on 2026-03-06 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_stockitems_cost_alter_stockitems_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='location_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='location_state',
            new_name='state',
        ),
    ]
