# Generated by Django 6.0.2 on 2026-03-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_cart_total_price_alter_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='supplier',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
