# Generated by Django 6.0.2 on 2026-03-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_cart_supplier'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('item', 'supplier'), name='unique_cart'),
        ),
    ]
