# Generated by Django 6.0.2 on 2026-03-16 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_cart_unique_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitems',
            name='initial_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='stockitems',
            name='restock_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='stockitems',
            name='stock',
            field=models.IntegerField(null=True, verbose_name='Stock Units'),
        ),
    ]
