# Generated by Django 6.0.2 on 2026-03-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_stockitems_initial_date_stockitems_restock_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitems',
            name='initial_date',
        ),
        migrations.RemoveField(
            model_name='stockitems',
            name='restock_date',
        ),
    ]
