# Generated by Django 6.0.2 on 2026-03-16 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_remove_stockitems_initial_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitems',
            name='initial_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='stockitems',
            name='restock_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
