# Generated by Django 6.0.3 on 2026-03-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_stockitems_deleted_at_stockitems_restored_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitems',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='stockitems',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='stockitems',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='transaction_id',
        ),
    ]
