# Generated by Django 6.0.3 on 2026-03-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_remove_stockitems_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitems',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
