# Generated by Django 6.0.3 on 2026-03-20 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_alter_cart_total_price_alter_customer_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasehistory',
            old_name='customer_name',
            new_name='customer_no',
        ),
    ]
