# Generated by Django 6.0.3 on 2026-03-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_rename_customer_name_purchasehistory_customer_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='customer_no',
            field=models.IntegerField(),
        ),
    ]
