# Generated by Django 6.0.3 on 2026-03-24 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_itemtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitems',
            name='item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.itemtype'),
        ),
    ]
