# Generated by Django 6.0.3 on 2026-03-24 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_stockitems_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitems',
            name='type',
        ),
    ]
