# Generated by Django 6.0.3 on 2026-03-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_remove_stockitems_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitems',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cost(Per Unit)'),
        ),
        migrations.AlterField(
            model_name='stockitems',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockitems',
            name='quantity',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Quantity(Per Unit)'),
        ),
        migrations.AlterField(
            model_name='stockitems',
            name='stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stock Units'),
        ),
    ]
