# Generated by Django 6.0.3 on 2026-03-25 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_alter_stockitems_cost_alter_stockitems_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitems',
            name='initial_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='stockitems',
            name='restock_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
