# Generated by Django 6.0.3 on 2026-03-25 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_alter_stockitems_initial_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000000000, message='Enter correct phone number'), django.core.validators.MaxValueValidator(9999999999, message='Enter correct phone number')]),
        ),
    ]
