# Generated by Django 6.0.3 on 2026-03-30 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_alter_supplier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1000000000, message='Enter correct phone number'), django.core.validators.MaxValueValidator(9999999999, message='Enter correct phone number')]),
        ),
    ]
