# Generated by Django 6.0.3 on 2026-03-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_supplier_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockitems',
            old_name='cost',
            new_name='mrp',
        ),
    ]
