# Generated by Django 6.0.3 on 2026-03-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_rename_cost_stockitems_mrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitems',
            name='cost_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cost Price(Per Unit)'),
        ),
        migrations.AlterField(
            model_name='stockitems',
            name='mrp',
            field=models.IntegerField(blank=True, null=True, verbose_name='MRP(Per Unit)'),
        ),
    ]
