# Generated by Django 6.0.3 on 2026-03-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_stockitems_cost_price_alter_stockitems_mrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitems',
            name='cost_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cost Price'),
        ),
        migrations.AlterField(
            model_name='stockitems',
            name='mrp',
            field=models.IntegerField(blank=True, null=True, verbose_name='MRP'),
        ),
    ]
