# Generated by Django 6.0.3 on 2026-04-01 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_alter_stockitems_cost_price_alter_stockitems_mrp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='itemtype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.itemtypecategory'),
        ),
    ]
