# Generated by Django 6.0.3 on 2026-04-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_itemtypecategory_itemtype_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('product_list', models.JSONField()),
                ('total_cost', models.IntegerField()),
                ('purchase_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
