# Generated by Django 6.0.3 on 2026-04-03 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_supplierhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField(default=1)),
                ('price', models.IntegerField(verbose_name='Price (per unit)')),
                ('total_price', models.IntegerField()),
                ('supplier', models.CharField(max_length=100)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.stockitems')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item', 'supplier'), name='unique_supply_cart')],
            },
        ),
    ]
