# Generated by Django 6.0.3 on 2026-04-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_suppliercart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliercart',
            name='units',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
