# Generated by Django 6.0.3 on 2026-04-08 07:34

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_alter_suppliercart_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.CharField(blank=True, null=True, verbose_name=inventory.models.StockItems),
        ),
    ]
