# Generated by Django 6.0.3 on 2026-04-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0048_alter_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='code',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
