# Generated by Django 6.0.3 on 2026-04-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_alter_itemtype_code_alter_itemtype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
