# Generated by Django 6.0.3 on 2026-04-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_itemtype_is_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitems',
            name='restock_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
