# Generated by Django 6.0.3 on 2026-04-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0052_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitems',
            name='cost_list',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='stockitems',
            name='expiry_date_list',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='stockitems',
            name='quantity_list',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='stockitems',
            name='restock_date_list',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='stockitems',
            name='stock_list',
            field=models.JSONField(default=list),
        ),
    ]
