# Generated by Django 6.0.3 on 2026-04-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0053_stockitems_cost_list_stockitems_expiry_date_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitems',
            name='cost_list',
        ),
        migrations.RemoveField(
            model_name='stockitems',
            name='expiry_date_list',
        ),
        migrations.RemoveField(
            model_name='stockitems',
            name='quantity_list',
        ),
        migrations.RemoveField(
            model_name='stockitems',
            name='restock_date_list',
        ),
        migrations.RemoveField(
            model_name='stockitems',
            name='stock_list',
        ),
    ]
