# Generated by Django 6.0.3 on 2026-05-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0054_remove_stockitems_cost_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_img',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
