# Generated by Django 6.0.3 on 2026-05-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0055_customer_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_img',
            field=models.ImageField(blank=True, default='media/images/default.jpg', null=True, upload_to='media/images/'),
        ),
    ]
