# Generated by Django 6.0.3 on 2026-05-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0056_alter_customer_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_img',
            field=models.ImageField(default='media/images/default.jpg', upload_to='media/images/'),
        ),
    ]
