# Generated by Django 6.0.3 on 2026-05-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0057_alter_customer_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitems',
            name='barcode',
            field=models.ImageField(default=None, null=True, upload_to='barcode/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_img',
            field=models.ImageField(default='media/images/default.jpg', upload_to='images/'),
        ),
    ]
