# Generated by Django 6.0.3 on 2026-05-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0058_stockitems_barcode_alter_customer_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitems',
            name='barcode',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='barcode/'),
        ),
    ]
