# Generated by Django 6.0.3 on 2026-05-16 05:41

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0059_alter_stockitems_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '200x200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
