# Generated by Django 6.0.3 on 2026-05-16 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0060_customer_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cropping',
        ),
    ]
